import { getConnection, safeExecuteDDL } from './lib/oracle.js';

export async function initializeSchema(): Promise<void> {
  const conn = await getConnection();
  try {
    // Sequences
    await safeExecuteDDL(conn, `CREATE SEQUENCE SYNC_LINK_SEQ START WITH 1 INCREMENT BY 1`);
    await safeExecuteDDL(conn, `CREATE SEQUENCE SYNC_EVENT_SEQ START WITH 1 INCREMENT BY 1`);
    await safeExecuteDDL(conn, `CREATE SEQUENCE SYNC_JOB_SEQ START WITH 1 INCREMENT BY 1`);
    await safeExecuteDDL(conn, `CREATE SEQUENCE SYNC_ATTEMPT_SEQ START WITH 1 INCREMENT BY 1`);
    await safeExecuteDDL(conn, `CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1`);

    // SYNC_LINK — one record per Zendesk ticket <-> ADO work item pair
    await safeExecuteDDL(conn, `
      CREATE TABLE SYNC_LINK (
        ID NUMBER DEFAULT SYNC_LINK_SEQ.NEXTVAL PRIMARY KEY,
        ZENDESK_TICKET_ID VARCHAR2(50) NOT NULL,
        ADO_ORG VARCHAR2(255) NOT NULL,
        ADO_PROJECT VARCHAR2(255) NOT NULL,
        ADO_WORK_ITEM_ID NUMBER NOT NULL,
        LINK_MODE VARCHAR2(20) NOT NULL,
        IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
        LAST_ZD_FINGERPRINT VARCHAR2(128),
        LAST_ADO_FINGERPRINT VARCHAR2(128),
        LAST_SYNC_SOURCE VARCHAR2(20),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        LAST_SYNCED_AT TIMESTAMP,
        CONSTRAINT CHK_LINK_MODE CHECK (LINK_MODE IN ('created', 'linked')),
        CONSTRAINT CHK_LINK_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
      )
    `);
    // Oracle 19c SE does not support partial/filtered unique indexes.
    // Enforce one-active-link-per-ticket via a unique function-based index instead.
    await safeExecuteDDL(conn, `CREATE UNIQUE INDEX IDX_SYNC_LINK_ACTIVE ON SYNC_LINK (CASE WHEN IS_ACTIVE = 1 THEN ZENDESK_TICKET_ID END)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_SYNC_LINK_TICKET ON SYNC_LINK (ZENDESK_TICKET_ID)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_SYNC_LINK_ADO ON SYNC_LINK (ADO_WORK_ITEM_ID)`);

    // SYNC_EVENT — durable inbound event ledger
    await safeExecuteDDL(conn, `
      CREATE TABLE SYNC_EVENT (
        ID NUMBER DEFAULT SYNC_EVENT_SEQ.NEXTVAL PRIMARY KEY,
        SOURCE_SYSTEM VARCHAR2(20) NOT NULL,
        SOURCE_EVENT_ID VARCHAR2(255),
        EVENT_TYPE VARCHAR2(128) NOT NULL,
        DEDUP_KEY VARCHAR2(512),
        PAYLOAD CLOB NOT NULL,
        PROCESSING_STATE VARCHAR2(20) DEFAULT 'received' NOT NULL,
        RECEIVED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT CHK_EVENT_SOURCE CHECK (SOURCE_SYSTEM IN ('zendesk', 'ado'))
      )
    `);
    await safeExecuteDDL(conn, `CREATE UNIQUE INDEX IDX_SYNC_EVENT_DEDUP ON SYNC_EVENT (DEDUP_KEY)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_SYNC_EVENT_TYPE ON SYNC_EVENT (SOURCE_SYSTEM, EVENT_TYPE)`);

    // SYNC_JOB — worker queue
    await safeExecuteDDL(conn, `
      CREATE TABLE SYNC_JOB (
        ID NUMBER DEFAULT SYNC_JOB_SEQ.NEXTVAL PRIMARY KEY,
        JOB_TYPE VARCHAR2(128) NOT NULL,
        RELATED_EVENT_ID NUMBER,
        RELATED_LINK_ID NUMBER,
        STATUS VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
        PAYLOAD CLOB,
        ATTEMPT_COUNT NUMBER DEFAULT 0 NOT NULL,
        MAX_ATTEMPTS NUMBER DEFAULT 5 NOT NULL,
        NEXT_PROCESS_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        STARTED_AT TIMESTAMP,
        FINISHED_AT TIMESTAMP,
        WORKER_ID VARCHAR2(64),
        ERROR_MESSAGE CLOB,
        DEDUP_KEY VARCHAR2(512),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT CHK_JOB_STATUS CHECK (STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'DEAD'))
      )
    `);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_SYNC_JOB_POLL ON SYNC_JOB (STATUS, NEXT_PROCESS_AT, ID)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_SYNC_JOB_LINK ON SYNC_JOB (RELATED_LINK_ID)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_SYNC_JOB_EVENT ON SYNC_JOB (RELATED_EVENT_ID)`);

    // SYNC_ATTEMPT — execution history per job attempt
    await safeExecuteDDL(conn, `
      CREATE TABLE SYNC_ATTEMPT (
        ID NUMBER DEFAULT SYNC_ATTEMPT_SEQ.NEXTVAL PRIMARY KEY,
        JOB_ID NUMBER NOT NULL,
        STARTED_AT TIMESTAMP NOT NULL,
        FINISHED_AT TIMESTAMP,
        RESULT VARCHAR2(20),
        ERROR_SUMMARY VARCHAR2(4000),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    `);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_SYNC_ATTEMPT_JOB ON SYNC_ATTEMPT (JOB_ID)`);

    // AUDIT_LOG — business-readable change history
    await safeExecuteDDL(conn, `
      CREATE TABLE AUDIT_LOG (
        ID NUMBER DEFAULT AUDIT_LOG_SEQ.NEXTVAL PRIMARY KEY,
        ACTION_TYPE VARCHAR2(128) NOT NULL,
        ACTOR_TYPE VARCHAR2(20) NOT NULL,
        SOURCE_SYSTEM VARCHAR2(20),
        TARGET_SYSTEM VARCHAR2(20),
        ZENDESK_TICKET_ID VARCHAR2(50),
        ADO_WORK_ITEM_ID VARCHAR2(50),
        SUMMARY VARCHAR2(4000),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    `);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_AUDIT_LOG_TICKET ON AUDIT_LOG (ZENDESK_TICKET_ID)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_AUDIT_LOG_ADO ON AUDIT_LOG (ADO_WORK_ITEM_ID)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_AUDIT_LOG_TIME ON AUDIT_LOG (CREATED_AT)`);

    // COMMENT_SYNC_MAP — dedupe mirrored comments in either direction.
    await safeExecuteDDL(conn, `
      CREATE TABLE COMMENT_SYNC_MAP (
        SOURCE_SYSTEM VARCHAR2(20) NOT NULL,
        SOURCE_COMMENT_ID VARCHAR2(255) NOT NULL,
        TARGET_SYSTEM VARCHAR2(20) NOT NULL,
        TARGET_COMMENT_ID VARCHAR2(255),
        ZENDESK_TICKET_ID VARCHAR2(50) NOT NULL,
        ADO_WORK_ITEM_ID NUMBER NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_COMMENT_SYNC_MAP PRIMARY KEY (SOURCE_SYSTEM, SOURCE_COMMENT_ID, TARGET_SYSTEM)
      )
    `);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_COMMENT_SYNC_TICKET ON COMMENT_SYNC_MAP (ZENDESK_TICKET_ID)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_COMMENT_SYNC_ADO ON COMMENT_SYNC_MAP (ADO_WORK_ITEM_ID)`);

    // ATTACHMENT_SYNC_MAP — dedupe Zendesk attachment uploads into ADO.
    await safeExecuteDDL(conn, `
      CREATE TABLE ATTACHMENT_SYNC_MAP (
        SOURCE_SYSTEM VARCHAR2(20) NOT NULL,
        SOURCE_ATTACHMENT_ID VARCHAR2(255) NOT NULL,
        TARGET_SYSTEM VARCHAR2(20) NOT NULL,
        TARGET_ATTACHMENT_URL VARCHAR2(1000),
        ZENDESK_TICKET_ID VARCHAR2(50) NOT NULL,
        ADO_WORK_ITEM_ID NUMBER NOT NULL,
        FILE_NAME VARCHAR2(512),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_ATTACHMENT_SYNC_MAP PRIMARY KEY (SOURCE_SYSTEM, SOURCE_ATTACHMENT_ID, TARGET_SYSTEM)
      )
    `);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_ATTACHMENT_SYNC_TICKET ON ATTACHMENT_SYNC_MAP (ZENDESK_TICKET_ID)`);
    await safeExecuteDDL(conn, `CREATE INDEX IDX_ATTACHMENT_SYNC_ADO ON ATTACHMENT_SYNC_MAP (ADO_WORK_ITEM_ID)`);

    // ITERATION_CACHE — sprint date cache
    await safeExecuteDDL(conn, `
      CREATE TABLE ITERATION_CACHE (
        ADO_PROJECT VARCHAR2(255) NOT NULL,
        ITERATION_PATH VARCHAR2(500) NOT NULL,
        DISPLAY_NAME VARCHAR2(255),
        START_DATE DATE,
        FINISH_DATE DATE,
        REFRESHED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_ITERATION_CACHE PRIMARY KEY (ADO_PROJECT, ITERATION_PATH)
      )
    `);

    console.log('[schema] Oracle schema initialized');
  } finally {
    await conn.close();
  }
}
